export const ACCESS_CODE_DEALERSHIP = 'ACCESS_CODE_DEALERSHIP';
export const ACCESS_CODE_PRIVATE_USER = 'ACCESS_CODE_PRIVATE_USER';
export const REGISTER_AUTH_USER = 'REGISTER_AUTH_USER'
export const REGISTER_USER_CAR_API = 'REGISTER_USER_CAR_API';
export const USER_API_UPDATE_AUTH_USER = 'USER_API_UPDATE_AUTH_USER';
export const USER_API_UPDATE_CAR_USER = 'USER_API_UPDATE_CAR_USER';
